#! /Users/ceich/.rvm/rubies/ruby-1.9.2-p320/bin/ruby

# Question 29:
# Consider all of the integer combinations for 2 < a < 5 and 2 < b < 5
# If they are then placed in numerical order and the duplicates are removed, 
# we get the following sequence of 15 distinct terms 
#    [4, 8, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125]
#
# How many distinct terms are generated by 2 < a < 100 and 2 < b <  100


combinations = []

# Double loop
(2..100).each do |a|
	(2..100).each do |b|
		combinations.push a**b
	end
end

# Remove duplicates
# combinations.sort!
combinations.uniq!

puts "Length: ", combinations.length, ""
# puts combinations
